apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-wide-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-wide-web
  template:
    metadata:
      labels:
        app: hello-world-wide-web
    spec:
      containers:
      - name: hello-world-wide-web
        image: vandric/hello-world-wide-web:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
